---
kind: pipeline
type: docker
name: verify

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.15
  commands:
  - go test ./... -cover -v

- name: lint
  image: golangci/golangci-lint:v1.35.2
  commands:
  - golangci-lint run

- name: build
  image: golang:1.15
  commands:
  - go build -ldflags "-X 'github.com/jones2026/fun-with-k8s/handlers.build=${DRONE_COMMIT}'" -o main
  environment:
    CGO_ENABLED: 0
    GOOS: linux

- name: docker_build
  image: plugins/docker
  settings:
    dry_run: true
    repo: pr
  when:
    event:
    - pull_request

- name: docker_publish
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO,,}
    tags:
    - latest
    - ${DRONE_COMMIT}
    username:
      from_secret: docker_username
  when:
    event:
    - push

trigger:
  branch:
  - main

---
kind: pipeline
type: docker
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: gcloud
  image: hashicorp/terraform
  commands:
  - echo $GCLOUD_SERVICE_KEY > $GOOGLE_APPLICATION_CREDENTIALS
  - cd terraform
  - export TF_VAR_api_version=${DRONE_COMMIT}
  - terraform init
  - terraform plan
  - terraform apply --auto-approve
  environment:
    GCLOUD_SERVICE_KEY:
      from_secret: GCLOUD_SERVICE_KEY
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json

- name: acceptance_test
  image: postman/newman
  commands:
  - source test.env
  - newman run fun-with-k8s.postman_collection.json --env-var base_url=$BASE_URL --env-var version=${DRONE_COMMIT}

trigger:
  branch:
  - main
  event:
  - push

depends_on:
- verify

...
