---
kind: pipeline
name: verify
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.15
  commands:
  - go test ./... -cover -v

- name: lint
  image: golangci/golangci-lint:v1.34.1
  commands:
  - golangci-lint run

- name: build
  image: golang:1.15
  commands:
  - go build -ldflags "-X 'github.com/jones2026/fun-with-k8s/handlers.build=${DRONE_COMMIT}'" -o main
  environment:
    CGO_ENABLED: 0
    GOOS: linux

- name: docker_build
  image: plugins/docker
  settings:
    dry_run: true
    repo: pr
  when:
    event:
    - pull_request

- name: docker_publish
  image: plugins/docker
  settings:
    auto_tag: true
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO,,}
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

trigger:
  branch:
  - main

---
kind: pipeline
name: deploy
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: gcloud
  image: hashicorp/terraform
  commands:
  - echo $GCLOUD_SERVICE_KEY > $GOOGLE_APPLICATION_CREDENTIALS
  - cd terraform
  - terraform plan
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
    GCLOUD_SERVICE_KEY:
      from_secret: GCLOUD_SERVICE_KEY


depends_on:
  - verify


...